### ISSUE TITLE
Create POJO for TorrentFile, Peer and FilePiece

### ISSUE THREAD

**Issue by yuchengu** [maxyu1115/owltorrent#8]

**Comment by maxyu1115** [comment]
I created stand ins to unblock others. https://github.com/maxyu1115/owltorrent/pull/9
(This issue still holds and not much has changed. )

**Comment by maxyu1115** [comment]
We want to discuss in class:
1. Torrent class should need Size of Pieces? (Array of sizes? )
2. Revise FilePiece. Should we have the hash, or the actual byte array? Or both?
